### ISSUE TITLE
v2.0.0 릴리즈

### ISSUE THREAD

**Issue by biyamn** [biyamn/Todolist#23]
- 필수 기능
  - [x] 초기 데이터 기입 (#24)
    - [x] 렌더링 오류 해결 1(#31)
    - [x] 렌더링 오류 해결 2(#33)
  - [x] 데이터 추가 순서대로 정렬 (#32) 
  - [x] 답변 현황 페이지 (#26)

- 추가 기능
  - [x] 반응형 레이아웃 (#27)
  - [x] 로딩 화면 (#29)
  - [x] 모바일 버전: '면접종류' 슬라이드 동작 (#28)
  - [x] 서비스 이용 가이드 페이지 (#34)
  - [ ] 테마 (#30)
  - [x] 파일명, 변수명, CSS 등 리팩토링
  - [x] 리드미, 릴리즈 버전 정리
